[build]
publish = "public"
command = "make production-build"

[build.environment]
HUGO_VERSION = "0.116.0"

[context.deploy-preview]
command = "make preview-build"

[context.branch-deploy]
command = "make preview-build"

# Docs redirects
[[redirects]]
from = "/docs/getting-started/"
to = "/docs/latest/getting-started/"
status = 302

[[redirects]]
from = "/docs/architecture/"
to = "/docs/latest/"
status = 302

[[redirects]]
from = "/docs/latest/*"
to = "/docs/2.3/:splat"
status = 302

# Social media
[[redirects]]
from = "/bsky"
to = "https://bsky.app/profile/did:plc:tnjzjt2e3o4w7oxyh3cedqsq/lists/3lcc4gw2asl2c"
status = 302

# Proposals
[[redirects]]
from = "/proposals/2026-release-cycle"
to = "https://docs.google.com/document/d/1RjFMBHLluYK9byUSz1IYgumPUMEqwNPTn890tg-IlCo/edit?tab=t.0"
status = 302

[[redirects]]
from = "/proposals/nri-ga-requirements"
to = "https://docs.google.com/document/d/1H9Tx6FgEhw_ep2eHgaV3_BZ-Zji1n_dOAD0VAD28YdE/edit?tab=t.0"
status = 302
